### ISSUE TITLE
Use onerror to detect errors instead of framework-specific hooks

### ISSUE THREAD

**Issue by asapach** [sergei-startsev/karma-stacktrace#3]
Use `window.addEventListener('error', ...)` instead of framework-specific logging hooks. This should allow to support any frameworks supported by Karma and log all errors only once.

Also update to https://github.com/stacktracejs/stacktrace.js/releases/tag/v2.0.0

**Comment by sergei-startsev** [comment]
Unfortunately there is no possibility to provide readable reporting based only on thrown errors - they does not contain any details about failed suites/specs. Error messages mostly include stacktrace information, that is not much useful itself when you have dozens failed tests and you would like to find corresponding stacktraces.

Moreover, Karma folks are going to get rid of throwing errors in `debug.js` in further releases: https://github.com/karma-runner/karma/commit/a36f3eb47408316686d1eeae4c54b6ca8edc54bd#diff-6436f8ea3757bd10bdfd554fc1711843

**Comment by sergei-startsev** [comment]
Regarding updating stacktrace.js I've opened another issues #4

**Comment by asapach** [comment]
Maybe catch all unhandled errors anyway to provide better stacktraces for them?

**Comment by sergei-startsev** [comment]
Let's wait when guys from Karma will release their [updates](https://github.com/karma-runner/karma/commit/a36f3eb47408316686d1eeae4c54b6ca8edc54bd#diff-6436f8ea3757bd10bdfd554fc1711843) in `debug.js`, otherwise all errors related to failed tests are will be caught as unhandled.

**Comment by sergei-startsev** [comment]
`debug.js` doesn't throw errors for failed tests since 1.7.1 version.
https://github.com/karma-runner/karma/blob/fe9a1dd13b5eb3969f9e08acbce020e2a382fd9e/static/debug.js#L19-L23

so I'm going to close this issue.
