### ISSUE TITLE
Cannot utilize plugin

### ISSUE THREAD

**Issue by Prinsn** [sergei-startsev/karma-stacktrace#7]
package
```    "jasmine-core": "^3.3.0",
    "jasmine-spec-reporter": "^4.2.1",
    "karma": "^4.0.1",
    "karma-chrome-launcher": "^2.2.0",
    "karma-coverage-istanbul-reporter": "^2.0.5",
    "karma-jasmine": "^2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "karma-junit-reporter": "^1.2.0",
    "karma-stacktrace": "^2.0.1",
```
karma
```
frameworks: [
      'jasmine',
      '@angular-devkit/build-angular',
      'karma-stacktrace'
    ],
    files: [
      'node_modules/jquery/dist/jquery.min.js',
      'node_modules/datatables.net/js/jquery.dataTables.js',
      'node_modules/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.js',
      'src/typings/model.d.ts'
    ],
    plugins: [
	require('karma-jasmine'),
        require('karma-chrome-launcher'),
        require('karma-jasmine-html-reporter'),
        require('karma-coverage-istanbul-reporter'),
        require('karma-junit-reporter'),
        require('karma-stacktrace'),
        require('@angular-devkit/build-angular/plugins/karma')
      ],
```

ng test ->
``` 10% building 2/2 modules 0 active26 07 2019 14:41:52.984:ERROR [karma-server]: Server start failed on port 9876: Error: No provider for "framework:karma-stacktrace"! (Resolving: framework:karma-stacktrace)```

**Comment by sergei-startsev** [comment]
Framework name isn't correct in your configuration:
```diff
- frameworks: ['karma-stacktrace']
+ frameworks: ['stacktrace']
```
See [Karma configuration](https://github.com/sergei-startsev/karma-stacktrace#karma-configuration).

**Comment by sergei-startsev** [comment]
@Prinsn Has the issue been resolved? btw you can also find an example of framework setup [here](https://github.com/sergei-startsev/karma-stacktrace/tree/master/examples/qunit).

**Comment by Prinsn** [comment]
Sorry, I'll look into it Monday, not a personal project.

I appreciate both the quick response and the follow up, however.

**Comment by Prinsn** [comment]
@sergei-startsev yeah, that works, thanks.

Sorry for the making my problems your problems.
